
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  Locale _locale = const Locale('en');

  LanguageProvider() {
    _loadLanguage();
  }

  Locale get locale => _locale;

  final List<Map<String, String>> supportedLanguages = [
    {'code': 'en', 'name': 'English', 'flag': '🇺🇸'},
    {'code': 'hi', 'name': 'हिंदी (Hindi)', 'flag': '🇮🇳'},
    {'code': 'es', 'name': 'Español (Spanish)', 'flag': '🇪🇸'},
    {'code': 'fr', 'name': 'Français (French)', 'flag': '🇫🇷'},
    {'code': 'de', 'name': 'Deutsch (German)', 'flag': '🇩🇪'},
  ];

  String getText(String key) {
    // Fallback to English if key or translation is missing
    return _localizedValues[_locale.languageCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }

  void changeLanguage(String languageCode) async {
    _locale = Locale(languageCode);
    SharedPreferences prefs = await SharedPreferences.getInstance();
    await prefs.setString('language_code', languageCode);
    notifyListeners();
  }

  void _loadLanguage() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    String? lang = prefs.getString('language_code');
    if (lang != null) {
      _locale = Locale(lang);
      notifyListeners();
    }
  }

  // --- THE DICTIONARY ---
  final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // General
      'app_name': 'EvesDrops',
      'close': 'Close',
      'loading': 'Loading...',
      'copy_code': 'Room code copied!',
      'error': 'Error',
      
      // Home & Settings
      'home': 'Home',
      'games': 'Games',
      'learn': 'Learn',
      'settings': 'Settings',
      'dark_mode': 'Dark Mode',
      'light_mode': 'Light Mode',
      'kinks': 'Kinks',
      'feedback': 'Feedback',
      'data_privacy': 'Data & Privacy',
      'languages': 'Languages',
      'report': 'Report Issue',
      'logout': 'Logout',
      'delete_account': 'Delete Account',
      'exit': 'Exit',
      'cancel': 'Cancel',
      'proceed': 'Proceed',

      // Learn Page
      'wellness_intimacy': 'Wellness & Intimacy',
      'read_guide': 'Read Guide',
      'sections_count': 'Sections',
      'takeaway': 'Takeaway',
      
      // Maze Game
      'maze': 'Intimacy Maze',
      'play_with_partner': 'Play with your partner',
      'play_offline': 'Play Offline (Local)',
      'or_online': '- OR ONLINE -',
      'create_online': 'Create Online Room',
      'enter_code': 'Enter 6-digit Room Code',
      'join_room': 'Join Room',
      'room': 'Room',
      'waiting_partner': 'Waiting for partner...',
      'your_turn': 'YOUR TURN',
      'partner_turn': 'PARTNER\'S TURN',
      'trap_msg': '⚠️ TRAP! Moved back 3 spaces!',
      'bonus_msg': '🌟 BONUS CELL! +20 Points!',
      'collision_msg': '💞 COLLISION! Love Bonus!',
      
      // Truth or Dare
      'truth_dare': 'Truth or Dare',
      'tap_reveal': 'Tap to Reveal',
      'truth': 'Truth',
      'dare': 'Dare',

      // 4 Cards
      '4_cards': '4 Cards',
      'task_prompt': 'Here is a task. Complete this challenge!',

      // Keyword Obsession (Categories)
      'keyword': 'Keyword Obsession',
      'Bondage': 'Bondage',
      'Toys': 'Toys',
      'Dominance/Submission': 'Dominance/Submission',
      'Oral': 'Oral',
      'Spanking': 'Spanking',
      'Food': 'Food',
      'Teasing/Denial': 'Teasing/Denial',
      'Anal': 'Anal',
      'Massage': 'Massage',
      'Kiss': 'Kiss',
      'Feet': 'Feet',
      'Music': 'Music',
      'Tantra': 'Tantra',
      'Roleplay': 'Roleplay',
      'Sensory Deprivation': 'Sensory Deprivation',
      'Alcohol': 'Alcohol',
      'Photo/Video': 'Photo/Video',
      'Porn': 'Porn',
      'Lipstick': 'Lipstick',
      'Penetration': 'Penetration',
      'Masturbation': 'Masturbation',
      'Lingerie': 'Lingerie',
      'Body Writing': 'Body Writing',
      'Breath Play': 'Breath Play',
      'Hair Play': 'Hair Play',
      'Scent Play': 'Scent Play',
      'Fantasy Sharing': 'Fantasy Sharing',
      'Tickling': 'Tickling',
      'Storytelling': 'Storytelling',
      'Striptease': 'Striptease',
      'Gamer': 'Gamer',
      'Nature': 'Nature',
      'Voyeurism': 'Voyeurism',
      'Exhibitionism': 'Exhibitionism',
      'Choking': 'Choking',
      'Light bondage': 'Light bondage',
      'next_task': 'Next Task',
      'no_more_tasks': 'No more tasks available!',
    },
    'hi': {
      'app_name': 'EvesDrops',
      'close': 'बंद करें',
      'loading': 'लोड हो रहा है...',
      'copy_code': 'रूम कोड कॉपी किया गया!',
      'error': 'त्रुटि',
      'home': 'होम',
      'games': 'खेल',
      'learn': 'सीखें',
      'settings': 'सेटिंग्स',
      'dark_mode': 'डार्क मोड',
      'light_mode': 'लाइट मोड',
      'kinks': 'पसंद (Kinks)',
      'feedback': 'प्रतिक्रिया',
      'data_privacy': 'डेटा और गोपनीयता',
      'languages': 'भाषाएं',
      'report': 'समस्या रिपोर्ट करें',
      'logout': 'लॉग आउट',
      'delete_account': 'खाता हटाएं',
      'exit': 'बाहर निकलें',
      'cancel': 'रद्द करें',
      'proceed': 'आगे बढ़ें',
      'wellness_intimacy': 'कल्याण और आत्मीयता',
      'read_guide': 'गाइड पढ़ें',
      'sections_count': 'भाग',
      'takeaway': 'निष्कर्ष',
      'maze': 'इंटीमेसी भूलभुलैया',
      'play_with_partner': 'अपने साथी के साथ खेलें',
      'play_offline': 'ऑफ़लाइन खेलें (लोकल)',
      'or_online': '- या ऑनलाइन -',
      'create_online': 'ऑनलाइन रूम बनाएं',
      'enter_code': '6 अंकों का कोड दर्ज करें',
      'join_room': 'रूम ज्वाइन करें',
      'room': 'रूम',
      'waiting_partner': 'साथी का इंतजार...',
      'your_turn': 'आपकी बारी',
      'partner_turn': 'साथी की बारी',
      'truth_dare': 'सच या हिम्मत',
      'tap_reveal': 'देखने के लिए टैप करें',
      'truth': 'सच',
      'dare': 'हिम्मत',
      '4_cards': '4 कार्ड्स',
      'task_prompt': 'यहाँ एक कार्य है। इसे पूरा करें!',
      'keyword': 'कीवर्ड ऑब्सेशन',
      'Bondage': 'बंधन',
      'Toys': 'खिलौने',
      'Dominance/Submission': 'प्रभुत्व/समर्पण',
      'Oral': 'मौखिक',
      'Massage': 'मालिश',
      'Kiss': 'चुंबन',
      'Feet': 'पैर',
      'Music': 'संगीत',
      'Roleplay': 'रोलप्ले',
      'next_task': 'अगला कार्य',
    },
    'es': {
      'app_name': 'EvesDrops',
      'close': 'Cerrar',
      'home': 'Inicio',
      'settings': 'Ajustes',
      'wellness_intimacy': 'Bienestar e Intimidad',
      'read_guide': 'Leer Guía',
      'sections_count': 'Secciones',
      'takeaway': 'Conclusión',
      'maze': 'Laberinto Íntimo',
      'play_with_partner': 'Juega con tu pareja',
      'play_offline': 'Jugar Offline (Local)',
      'or_online': '- O EN LÍNEA -',
      'create_online': 'Crear Sala Online',
      'enter_code': 'Código de 6 dígitos',
      'join_room': 'Unirse a Sala',
      'room': 'Sala',
      'waiting_partner': 'Esperando pareja...',
      'your_turn': 'TU TURNO',
      'partner_turn': 'TURNO DE PAREJA',
      'truth_dare': 'Verdad o Reto',
      'tap_reveal': 'Toca para Revelar',
      'truth': 'Verdad',
      'dare': 'Reto',
      '4_cards': '4 Cartas',
      'task_prompt': 'Aquí tienes una tarea. ¡Complétala!',
      'keyword': 'Obsesión',
      'Bondage': 'Bondage',
      'Toys': 'Juguetes',
      'Dominance/Submission': 'Dominación/Sumisión',
      'Oral': 'Oral',
      'Massage': 'Masaje',
      'Kiss': 'Beso',
      'next_task': 'Siguiente Tarea',
    },
    'fr': {
      'app_name': 'EvesDrops',
      'close': 'Fermer',
      'home': 'Accueil',
      'settings': 'Paramètres',
      'wellness_intimacy': 'Bien-être et Intimité',
      'read_guide': 'Lire le Guide',
      'sections_count': 'Sections',
      'takeaway': 'À retenir',
      'maze': 'Labyrinthe',
      'play_with_partner': 'Jouez avec votre partenaire',
      'play_offline': 'Jouer Hors Ligne',
      'or_online': '- OU EN LIGNE -',
      'create_online': 'Créer une Salle',
      'enter_code': 'Code à 6 chiffres',
      'join_room': 'Rejoindre',
      'room': 'Salle',
      'waiting_partner': 'En attente...',
      'your_turn': 'À VOUS',
      'partner_turn': 'TOUR DU PARTENAIRE',
      'truth_dare': 'Action ou Vérité',
      'tap_reveal': 'Appuyez pour Révéler',
      'truth': 'Vérité',
      'dare': 'Action',
      '4_cards': '4 Cartes',
      'task_prompt': 'Voici une tâche. Relevez le défi !',
      'keyword': 'Mots Clés',
      'Bondage': 'Bondage',
      'Toys': 'Jouets',
      'Dominance/Submission': 'Domination/Soumission',
      'Oral': 'Oral',
      'Massage': 'Massage',
      'Kiss': 'Baiser',
      'next_task': 'Tâche Suivante',
    },
    'de': {
      'app_name': 'EvesDrops',
      'close': 'Schließen',
      'home': 'Startseite',
      'settings': 'Einstellungen',
      'wellness_intimacy': 'Wellness & Intimität',
      'read_guide': 'Anleitung lesen',
      'sections_count': 'Abschnitte',
      'takeaway': 'Fazit',
      'maze': 'Labyrinth',
      'play_with_partner': 'Spiel mit deinem Partner',
      'play_offline': 'Offline spielen',
      'or_online': '- ODER ONLINE -',
      'create_online': 'Online-Raum erstellen',
      'enter_code': '6-stelliger Code',
      'join_room': 'Raum beitreten',
      'room': 'Raum',
      'waiting_partner': 'Warten auf Partner...',
      'your_turn': 'DU BIST DRAN',
      'partner_turn': 'PARTNER IST DRAN',
      'truth_dare': 'Wahrheit/Pflicht',
      'tap_reveal': 'Tippen zum Aufdecken',
      'truth': 'Wahrheit',
      'dare': 'Pflicht',
      '4_cards': '4 Karten',
      'task_prompt': 'Hier ist eine Aufgabe. Erledige sie!',
      'keyword': 'Stichwort',
      'Bondage': 'Fesselspiele',
      'Toys': 'Spielzeug',
      'Dominance/Submission': 'Dominanz/Unterwerfung',
      'Oral': 'Oral',
      'Massage': 'Massage',
      'Kiss': 'Kuss',
      'next_task': 'Nächste Aufgabe',
    },
  };
}