// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHOs8HNG4GIGF3Td-Vw4WAWBjURmj-c3o',
    appId: '1:828216880386:web:1e6644384f07f5b92fe61b',
    messagingSenderId: '828216880386',
    projectId: 'evesdrops-46b4b',
    authDomain: 'evesdrops-46b4b.firebaseapp.com',
    storageBucket: 'evesdrops-46b4b.firebasestorage.app',
    measurementId: 'G-R3EXQ615E4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdceP3x7glrNq46CAQNzYdcCicNMTfC70',
    appId: '1:828216880386:android:cd606e98e9ceffaf2fe61b',
    messagingSenderId: '828216880386',
    projectId: 'evesdrops-46b4b',
    storageBucket: 'evesdrops-46b4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxUbdiUthWmAGpA_sBk92mNAsUz3DLL-Q',
    appId: '1:828216880386:ios:4273c3a23104fc8b2fe61b',
    messagingSenderId: '828216880386',
    projectId: 'evesdrops-46b4b',
    storageBucket: 'evesdrops-46b4b.firebasestorage.app',
    iosClientId: '828216880386-llqkcc3ll3hm49ett5a0aoe62s5r5vt6.apps.googleusercontent.com',
    iosBundleId: 'com.example.curve',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxUbdiUthWmAGpA_sBk92mNAsUz3DLL-Q',
    appId: '1:828216880386:ios:4273c3a23104fc8b2fe61b',
    messagingSenderId: '828216880386',
    projectId: 'evesdrops-46b4b',
    storageBucket: 'evesdrops-46b4b.firebasestorage.app',
    iosClientId: '828216880386-llqkcc3ll3hm49ett5a0aoe62s5r5vt6.apps.googleusercontent.com',
    iosBundleId: 'com.example.curve',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHOs8HNG4GIGF3Td-Vw4WAWBjURmj-c3o',
    appId: '1:828216880386:web:67a5f0d05130d7f12fe61b',
    messagingSenderId: '828216880386',
    projectId: 'evesdrops-46b4b',
    authDomain: 'evesdrops-46b4b.firebaseapp.com',
    storageBucket: 'evesdrops-46b4b.firebasestorage.app',
    measurementId: 'G-0F4RX8WC1P',
  );
}
